Prepare PyPI page
m1kit/yalm-python pull request #21
Opened 2021-08-04 17:09 UTC by m1kit

2021-08-05 16:27 UTC, m1kit commented
Hi @goneall, @anshuldutt21,

I'd like to ask you two to review the new README.md.
You can check it [here](https://github.com/m1kit/yalm-python/blob/feature/pypi/README.md) (features/how-to-use parts are still in WIP since we don't have finalized our API interface).

Especially, I want to hear from @anshuldutt21. 
I respect your contribution to this library, but the first few lines of README.md are a very important place to describe this library especially on PyPI. I moved credits and license information to the bottom. Please let me know if it is okay with you.

2021-08-05 22:54 UTC, goneall requested changes
The structure of the README looks OK to me.  I had a couple of comments below related to contributing and license sections.

2021-08-05 22:54 UTC, goneall commented on README.md
> +
I would suggest adding a separate sub-heading `## Credits` here

2021-08-05 22:54 UTC, goneall commented on README.md
> +## Contributing
In the contributing, we should add a reference to Developer Certificate of Origin.  For an example, see the [tools-python contribution licensing section](https://github.com/spdx/tools-python/blob/main/CONTRIBUTING.MD#licensing).

More of a style comment, but I prefer to have the contributing separated out from the README - as a CONTRIBUTING.MD file.

2021-08-06 10:43 UTC, anshuldutt21 commented on README.md
>  ```
I think we could add commands for using a virtual python environment of version 3.9 or higher as was used in the earlier case. Also, just for confirmation, you would be adding some examples here too for the license matching implementations as to how to use the library in the future, right?

2021-08-06 13:34 UTC, m1kit commented on README.md
>  ```
> using a virtual python environment 
I think the virtual environment setting is a matter of preference for each user...?
At this moment `pip` does almost everything for us, I don't think we need to force using a virtual env.

2021-08-07 18:42 UTC, m1kit commented on README.md
> +## Contributing
@goneall
I added CONTRIBUTING.md and almost copy-pasted lines from `tools-python`.

(Apart from that, I tried to run the command for signing past commits and found the history for this branch is messed. Maybe I should fix this...😔 )

BTW, I sent you an email about the meeting time, but I received a delivery error message. In case you have not received it, I'd like to inform you that 16:00UTC is okay for me.

2021-08-08 03:56 UTC, goneall approved these changes
LGTM

2021-08-08 03:57 UTC, goneall commented on README.md
> +## Contributing
Changes look good.  Thanks @m1kit

2021-08-08 05:50 UTC, merged